### ISSUE TITLE
Support gmake

### ISSUE THREAD

**Issue by mcandre** [fadado/yummy#3]
In Mac OS, the easiest way to update make from the Xcode 7.3.1-provided make v3.81 to v3.82+ is via Homebrew, which provides GNU Make (gmake) v4.2.1 from homebrew/dupes/make.

However, when I try to use gmake to build and install yummy, I get a syntax error:

```
$ gmake install
id: illegal option -- -
usage: id [user]
       id -A
       id -F [user]
       id -G [-n] [user]
       id -M
       id -P [user]
       id -g [-nr] [user]
       id -p [user]
       id -u [-nr] [user]
gmake: *** [Makefile:36: install] Error 1
```

**Comment by fadado** [comment]
Portability is not an objective at this stage of development.
